model:
  name: ResNet50
  cls: "segmentation"
  num_classes: 37

num_classes: 37


epsilon: 8.0
warm_epochs: 0
grad_clip: 5.0
adv_train_type:
  name: TradesLoss
  alpha: 6.0
  mtype: "segmentation"
  num_steps: 10
  return_x: True

withat: True
withknowledge: True

awp: True
awp_warmup: 20
beta: 6.0
awp_gamma: 0.005

root: "/home/lixiao/data/VOCdevkitv3/VOC2010/"
subroot: "ImageSets/PartSeg_strategy4"
finegrained: False
knowledge: Pascal_part_connection

amp: True
batch_per_gpu: 32
learning_rate: 0.1
epochs: 300
adv_eval_epoch: 0.9
log_frequency: 20
ignare_label: 255

traindataset:
  name: VOCDataset
  list_path: "ImageSets/PartSeg_strategy4/train.txt"
  Part_Seg_folder: "PartSeg_strategy4"
  mode: "train" 
  ignore_label: 255

testdataset:
  name: VOCDataset
  list_path: "ImageSets/PartSeg_strategy4/val.txt"
  Part_Seg_folder: "PartSeg_strategy4"
  mode: "test" 
  ignore_label: 255
  scale: False
  mirror: False