model:
  name: ResNet50
  cls: "standard"
  num_classes: 10

num_classes: 10
epsilon: 1.0

root: "/home/lixiao/data/VOCdevkitv3/VOC2010/"
subroot: "ImageSets/PartSeg_strategy4"
finegrained: False
knowledge: Pascal_part_connection

batch_per_gpu: 32
learning_rate: 0.1
epochs: 200
adv_eval_epoch: 0.9
log_frequency: 20
ignare_label: 255

traindataset:
  name: VOCDataset
  list_path: "ImageSets/PartSeg_strategy4/train.txt"
  Part_Seg_folder: "PartSeg_strategy4"
  mode: "train" 
  ignore_label: 255

testdataset:
  name: VOCDataset
  list_path: "ImageSets/PartSeg_strategy4/val.txt"
  Part_Seg_folder: "PartSeg_strategy4"
  mode: "test" 
  ignore_label: 255
  scale: False
  mirror: False