model:
  name: UNet
  n_classes: 504
  cls: "segmentation"

num_classes: 504

epsilon: 8.0
single_step: 2.0
warm_epochs: 0
grad_clip: 5.0
adv_train_type:
  name: TradesLoss
  alpha: 6.0
  mtype: "segmentation"
  num_steps: 5
  return_x: True

awp: True
awp_warmup: 0
beta: 6.0
awp_gamma: 0.005

ema: True


withat: True
withknowledge: True
root: "/home/lixiao/ssd/PartImageNet/"
subroot: "reduceannotations"
finegrained: True
knowledge: PartImageNet_connection

amp: True
batch_per_gpu: 28
learning_rate: 0.1
epochs: 300
adv_eval_epoch: 0.9
log_frequency: 20
ignare_label: 255

traindataset:
  name: CocoDataset
  mode: "train"
  anns: "reduceannotations"
  supercategory:  False

testdataset:
  name: CocoDataset
  mode: "test"
  anns: "reduceannotations"
  supercategory:  False